###############################################################################
## Main Settings
###############################################################################
baseURL = "https://example.com"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Manuel Gil :: Software Engineer"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
# disqusShortname = ""

# Google Analytics
# googleAnalytics = "UA-123-45"

###############################################################################
## Params
###############################################################################
[params]
title = "Manuel Gil"
author = "Manuel Gil"
description = "Software Engineer | Computer Graphics | C++/Rust"
profilePicture = "images/profile.jpg"
keywords = ""
favicon = "favicons/"
customCss = ["css/custom.css"]
customJs = []
mainSections = ["post"]
defaultPage = "about"
images = ["images/site-feature-image.png"]
doNotLoadAnimations = true
# Google Site Verification
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"

###############################################################################
## Math settings
###############################################################################
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

###############################################################################
## Social links
###############################################################################
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://linkedin.com/manuel.gil"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/manugildev"

#[[params.socialIcons]]
#icon = "fab fa-instagram"
#title = "instagram"
#url = "https://www.instagram.com/"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:manugildev@gmail.com"

###############################################################################
## Menu items
###############################################################################
[menu]

  [[menu.main]]
  name = "Home"
  identifier = "about"
  weight = 100
  url = "/"
#
#  [[menu.main]]
#  name = "Posts"
#  weight = 200
#  identifier = "posts"
#  url = "/post/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about"
